# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14e51cf604b48a0cb2338a9da41fb42744ffabee03abd440c03d7b9d301dec5177be28726d2f57997180e546cc36f967cc63bbc687930408c4fd7ac61bddd71

test:
  secret_key_base: 2c38080587be0488c7fdd7a1767e3fb77e23f7a42dce70afae43e54efcb199d94accbf29199c6bd8ee10728ccfb8dd3e5da5ecfb7d63809306b38d47bb25d639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
